# compose.yml
services:
  vector:
    image: timberio/vector:0.48.0-debian
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
      - ./data/vector-logs:/var/log

    ports:
      - "9090:9090"     # Prometheus exporter
      - "8686:8686"     # Admin API
      - "8125:8125/udp" # DogStatsD (optional)




  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    depends_on:
      vector:
        condition: service_started
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_DOMAIN=localhost
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

    depends_on:
      prometheus:
        condition: service_started
    restart: unless-stopped


  go-api:
    build: ./go-api
    environment:
      - STATSD_ADDR=vector:8125
      - LOG_TARGET=vector:9000
      - SERVICE_NAME=api
      - ENV=dev
    depends_on:
      vector:
        condition: service_started
    ports:
      - "8080:8080"
    restart: unless-stopped
