# compose.yml
services:
  vector:
    image: timberio/vector:0.48.0-debian
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
      - ./data/vector-logs:/var/log
    ports:
      - "9090:9090"     # Prometheus exporter
      - "8686:8686"     # Admin API
      - "8125:8125/udp" # DogStatsD (optional)




  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./prometheus:/etc/prometheus:ro
    ports:
      - "9091:9090"
    depends_on:
      vector:
        condition: service_started

    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    command: ["--config.file=/etc/alertmanager/alertmanager.yml"]
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    restart: unless-stopped

  webhook:
    build: ./webhook
    ports:
      - "9094:8080"
    restart: unless-stopped

  demo-ui:
    build: ./demo-ui
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=development
    depends_on:
      - controller
      - go-api
      - prometheus
    restart: unless-stopped



  controller:
    build: ./controller
    environment:
      - PROM_URL=http://prometheus:9090
      - API_URL=http://go-api:8080
      - INTERVAL=3
      - WINDOW=30s
      - SERVICE=api
      - ENV=dev
      - ERR_HIGH=0.05
      - ERR_LOW=0.01
      - LAT_HIGH=0.35
      - LAT_LOW=0.20
      - MIN_RATE=0.1
      - MAX_RATE=1.0
      - STEP=0.1
      - COOLDOWN_SEC=10
    depends_on:
      prometheus:
        condition: service_started
      go-api:
        condition: service_started
    ports:
      - "9095:8080"  # controller webhook/health
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_DOMAIN=localhost
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

    depends_on:
      prometheus:
        condition: service_started

    restart: unless-stopped


  go-api:
    build: ./go-api
    environment:
      - STATSD_ADDR=vector:8125
      - LOG_TARGET=vector:9000
      - SERVICE_NAME=api
      - ENV=dev
    depends_on:
      vector:
        condition: service_started
    ports:
      - "8080:8080"
    restart: unless-stopped


networks:
  default:
    driver: bridge
