# prometheus.yml
global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "vector"
    static_configs:
      - targets: ["vector:9090"]

  - job_name: "go-api"
    static_configs:
      - targets: ["go-api:8080"]

