# prometheus.yml
global:
  scrape_interval: 1s
  evaluation_interval: 1s
  scrape_timeout: 1s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "vector"
    static_configs:
      - targets: ["vector:9090"]
    scrape_interval: 1s
    scrape_timeout: 1s

  - job_name: "go-api"
    static_configs:
      - targets: ["go-api:8080"]
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics

  - job_name: "controller"
    static_configs:
      - targets: ["controller:8080"]
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics

